/* tslint:disable */

export const MOCK_MESSAGES = [
    {
        "id": 2426,
        "created": "2017-09-27T17:04:23Z",
        "updated": "2017-09-27T17:04:23Z",
        "author": {
            "id": 102484,
            "password": "pbkdf2_sha256$30000$RFWNHBERcJ3M$51DrnOHueaOQm/u3xVHS3EuzRQUC66VB0IgKOKtd37s=",
            "last_login": "2017-11-21T23:37:25Z",
            "is_superuser": false,
            "first_name": "Kailin",
            "middle_initial": "",
            "last_name": "Parent",
            "street_address": null,
            "city": null,
            "state": null,
            "zipcode": null,
            "email": "kj.parent@example.com",
            "gender": null,
            "photo_url": null,
            "profile_photo": null,
            "anon_app_id": null,
            "first_login_date": "2017-09-25T15:55:15Z",
            "force_task_regeneration": false,
            "is_new_academic_year": false,
            "has_transitioned": false,
            "has_updated_application_dates": false,
            "is_active": true,
            "is_admin": false,
            "meta": null,
            "registration_date": "2017-09-25T15:55:15Z",
            "stakeholder_type": "Parent",
            "terms_of_service": false,
            "verified": false,
            "ambassador_uid": "ec239d9d-85cb-45e8-b341-ef6b4a30ae4e",
            "class_rank": null,
            "class_rank_type": "None",
            "class_size": null,
            "gpa": null,
            "gpa_scale": "4.0",
            "graduation_year": null,
            "has_letters": false,
            "is_ambassador": false,
            "phase": "Parent",
            "points": 0,
            "sisid": null,
            "weighted": "Unknown",
            "date_of_birth": null,
            "age": null,
            "has_used_other_names": false,
            "former_last_name": null,
            "occupation": null,
            "education_level": null,
            "education_level_status": null,
            "highest_education_level_desired": null,
            "police_record": false,
            "police_record_explanation": null,
            "interest_profiler_result": {},
            "waived_ferpa": false,
            "district": null,
            "highschool": null,
            "parents_marital_status": null,
            "marital_status": null,
            "groups": [],
            "user_permissions": [],
            "references": [],
            "potential_majors": [],
            "citizenships": [],
            "courses": [],
            "honors": [],
            "activities": [],
            "organizations": [],
            "languages": [],
            "interests": [],
            "military_affiliations": [],
            "ethnicities": [],
            "religions": [],
            "sports": [],
            "career_interests": []
        },
        "task": {
            "id": 463891,
            "completed": false,
            "completed_on": null,
            "created_on": "2017-09-15",
            "updated_on": "2017-09-27T17:04:29Z",
            "app_type": null,
            "verified_on": null,
            "status": "ST",
            "started_on": "2017-09-19",
            "begin_date": "2017-09-16",
            "deadline": "2017-09-30",
            "archived": false,
            "counselor_due_date": null,
            "counselor_start_date": null,
            "attachment": "https://next-tier-test.s3.amazonaws.com/task_attachment/463891/20170927170429.png?Signature=VVJwTqE5nchXDfV80qA1TfflZU0%3D&Expires=1511838989&AWSAccessKeyId=AKIAJN7I3BGSWGOYIK4Q",
            "attachment_file_name": "dino copy.png",
            "task": 515962,
            "student": 102373,
            "institution": null,
            "verified_by": null
        },
        "note": "HiiiI!"
    },
    {
        "id": 2446,
        "created": "2017-11-28T02:12:24Z",
        "updated": "2017-11-28T02:12:24Z",
        "author": {
            "id": 102373,
            "password": "pbkdf2_sha256$30000$0M3DBUAlXzT2$RomjI/ofaJ+1nuwMdOtlVwZO8wdEK8BnlN2dtm7GzWY=",
            "last_login": "2017-11-28T01:58:11Z",
            "is_superuser": false,
            "first_name": "Kailin",
            "middle_initial": "",
            "last_name": "Johnson",
            "street_address": null,
            "city": null,
            "state": null,
            "zipcode": null,
            "email": "kj@example.com",
            "gender": null,
            "photo_url": null,
            "profile_photo": null,
            "anon_app_id": null,
            "first_login_date": "2017-08-31T19:10:23Z",
            "force_task_regeneration": false,
            "is_new_academic_year": false,
            "has_transitioned": false,
            "has_updated_application_dates": false,
            "is_active": true,
            "is_admin": false,
            "meta": null,
            "registration_date": "2017-08-31T19:10:23Z",
            "stakeholder_type": "Student",
            "terms_of_service": false,
            "verified": false,
            "ambassador_uid": "e3482dd9-1b2b-4414-a8a1-ca0bea076d1b",
            "class_rank": null,
            "class_rank_type": "None",
            "class_size": null,
            "gpa": null,
            "gpa_scale": "4.0",
            "graduation_year": 2018,
            "has_letters": false,
            "is_ambassador": false,
            "phase": "Senior",
            "points": 3400,
            "sisid": null,
            "weighted": "Unknown",
            "date_of_birth": null,
            "age": null,
            "has_used_other_names": false,
            "former_last_name": null,
            "occupation": null,
            "education_level": null,
            "education_level_status": null,
            "highest_education_level_desired": null,
            "police_record": false,
            "police_record_explanation": null,
            "interest_profiler_result": [
                {
                    "score": 11,
                    "area": "Realistic"
                },
                {
                    "score": 11,
                    "area": "Investigative"
                },
                {
                    "score": 6,
                    "area": "Artistic"
                },
                {
                    "score": 14,
                    "area": "Social"
                },
                {
                    "score": 11,
                    "area": "Enterprising"
                },
                {
                    "score": 9,
                    "area": "Conventional"
                }
            ],
            "waived_ferpa": false,
            "district": 5,
            "highschool": 41786,
            "parents_marital_status": null,
            "marital_status": null,
            "groups": [],
            "user_permissions": [],
            "references": [],
            "potential_majors": [],
            "citizenships": [],
            "courses": [],
            "honors": [],
            "activities": [],
            "organizations": [],
            "languages": [],
            "interests": [],
            "military_affiliations": [],
            "ethnicities": [],
            "religions": [],
            "sports": [],
            "career_interests": []
        },
        "task": {
            "id": 463891,
            "completed": false,
            "completed_on": null,
            "created_on": "2017-09-15",
            "updated_on": "2017-09-27T17:04:29Z",
            "app_type": null,
            "verified_on": null,
            "status": "ST",
            "started_on": "2017-09-19",
            "begin_date": "2017-09-16",
            "deadline": "2017-09-30",
            "archived": false,
            "counselor_due_date": null,
            "counselor_start_date": null,
            "attachment": "https://next-tier-test.s3.amazonaws.com/task_attachment/463891/20170927170429.png?Signature=VVJwTqE5nchXDfV80qA1TfflZU0%3D&Expires=1511838989&AWSAccessKeyId=AKIAJN7I3BGSWGOYIK4Q",
            "attachment_file_name": "dino copy.png",
            "task": 515962,
            "student": 102373,
            "institution": null,
            "verified_by": null
        },
        "note": "ooooh"
    },
    {
        "id": 2447,
        "created": "2017-11-28T02:13:20Z",
        "updated": "2017-11-28T02:13:20Z",
        "author": {
            "id": 102373,
            "password": "pbkdf2_sha256$30000$0M3DBUAlXzT2$RomjI/ofaJ+1nuwMdOtlVwZO8wdEK8BnlN2dtm7GzWY=",
            "last_login": "2017-11-28T01:58:11Z",
            "is_superuser": false,
            "first_name": "Kailin",
            "middle_initial": "",
            "last_name": "Johnson",
            "street_address": null,
            "city": null,
            "state": null,
            "zipcode": null,
            "email": "kj@example.com",
            "gender": null,
            "photo_url": null,
            "profile_photo": null,
            "anon_app_id": null,
            "first_login_date": "2017-08-31T19:10:23Z",
            "force_task_regeneration": false,
            "is_new_academic_year": false,
            "has_transitioned": false,
            "has_updated_application_dates": false,
            "is_active": true,
            "is_admin": false,
            "meta": null,
            "registration_date": "2017-08-31T19:10:23Z",
            "stakeholder_type": "Student",
            "terms_of_service": false,
            "verified": false,
            "ambassador_uid": "e3482dd9-1b2b-4414-a8a1-ca0bea076d1b",
            "class_rank": null,
            "class_rank_type": "None",
            "class_size": null,
            "gpa": null,
            "gpa_scale": "4.0",
            "graduation_year": 2018,
            "has_letters": false,
            "is_ambassador": false,
            "phase": "Senior",
            "points": 3400,
            "sisid": null,
            "weighted": "Unknown",
            "date_of_birth": null,
            "age": null,
            "has_used_other_names": false,
            "former_last_name": null,
            "occupation": null,
            "education_level": null,
            "education_level_status": null,
            "highest_education_level_desired": null,
            "police_record": false,
            "police_record_explanation": null,
            "interest_profiler_result": [
                {
                    "score": 11,
                    "area": "Realistic"
                },
                {
                    "score": 11,
                    "area": "Investigative"
                },
                {
                    "score": 6,
                    "area": "Artistic"
                },
                {
                    "score": 14,
                    "area": "Social"
                },
                {
                    "score": 11,
                    "area": "Enterprising"
                },
                {
                    "score": 9,
                    "area": "Conventional"
                }
            ],
            "waived_ferpa": false,
            "district": 5,
            "highschool": 41786,
            "parents_marital_status": null,
            "marital_status": null,
            "groups": [],
            "user_permissions": [],
            "references": [],
            "potential_majors": [],
            "citizenships": [],
            "courses": [],
            "honors": [],
            "activities": [],
            "organizations": [],
            "languages": [],
            "interests": [],
            "military_affiliations": [],
            "ethnicities": [],
            "religions": [],
            "sports": [],
            "career_interests": []
        },
        "task": {
            "id": 463891,
            "completed": false,
            "completed_on": null,
            "created_on": "2017-09-15",
            "updated_on": "2017-09-27T17:04:29Z",
            "app_type": null,
            "verified_on": null,
            "status": "ST",
            "started_on": "2017-09-19",
            "begin_date": "2017-09-16",
            "deadline": "2017-09-30",
            "archived": false,
            "counselor_due_date": null,
            "counselor_start_date": null,
            "attachment": "https://next-tier-test.s3.amazonaws.com/task_attachment/463891/20170927170429.png?Signature=VVJwTqE5nchXDfV80qA1TfflZU0%3D&Expires=1511838989&AWSAccessKeyId=AKIAJN7I3BGSWGOYIK4Q",
            "attachment_file_name": "dino copy.png",
            "task": 515962,
            "student": 102373,
            "institution": null,
            "verified_by": null
        },
        "note": "noice"
    },
    {
        "id": 2448,
        "created": "2017-11-28T02:13:24Z",
        "updated": "2017-11-28T02:13:24Z",
        "author": {
            "id": 102373,
            "password": "pbkdf2_sha256$30000$0M3DBUAlXzT2$RomjI/ofaJ+1nuwMdOtlVwZO8wdEK8BnlN2dtm7GzWY=",
            "last_login": "2017-11-28T01:58:11Z",
            "is_superuser": false,
            "first_name": "Kailin",
            "middle_initial": "",
            "last_name": "Johnson",
            "street_address": null,
            "city": null,
            "state": null,
            "zipcode": null,
            "email": "kj@example.com",
            "gender": null,
            "photo_url": null,
            "profile_photo": null,
            "anon_app_id": null,
            "first_login_date": "2017-08-31T19:10:23Z",
            "force_task_regeneration": false,
            "is_new_academic_year": false,
            "has_transitioned": false,
            "has_updated_application_dates": false,
            "is_active": true,
            "is_admin": false,
            "meta": null,
            "registration_date": "2017-08-31T19:10:23Z",
            "stakeholder_type": "Student",
            "terms_of_service": false,
            "verified": false,
            "ambassador_uid": "e3482dd9-1b2b-4414-a8a1-ca0bea076d1b",
            "class_rank": null,
            "class_rank_type": "None",
            "class_size": null,
            "gpa": null,
            "gpa_scale": "4.0",
            "graduation_year": 2018,
            "has_letters": false,
            "is_ambassador": false,
            "phase": "Senior",
            "points": 3400,
            "sisid": null,
            "weighted": "Unknown",
            "date_of_birth": null,
            "age": null,
            "has_used_other_names": false,
            "former_last_name": null,
            "occupation": null,
            "education_level": null,
            "education_level_status": null,
            "highest_education_level_desired": null,
            "police_record": false,
            "police_record_explanation": null,
            "interest_profiler_result": [
                {
                    "score": 11,
                    "area": "Realistic"
                },
                {
                    "score": 11,
                    "area": "Investigative"
                },
                {
                    "score": 6,
                    "area": "Artistic"
                },
                {
                    "score": 14,
                    "area": "Social"
                },
                {
                    "score": 11,
                    "area": "Enterprising"
                },
                {
                    "score": 9,
                    "area": "Conventional"
                }
            ],
            "waived_ferpa": false,
            "district": 5,
            "highschool": 41786,
            "parents_marital_status": null,
            "marital_status": null,
            "groups": [],
            "user_permissions": [],
            "references": [],
            "potential_majors": [],
            "citizenships": [],
            "courses": [],
            "honors": [],
            "activities": [],
            "organizations": [],
            "languages": [],
            "interests": [],
            "military_affiliations": [],
            "ethnicities": [],
            "religions": [],
            "sports": [],
            "career_interests": []
        },
        "task": {
            "id": 463891,
            "completed": false,
            "completed_on": null,
            "created_on": "2017-09-15",
            "updated_on": "2017-09-27T17:04:29Z",
            "app_type": null,
            "verified_on": null,
            "status": "ST",
            "started_on": "2017-09-19",
            "begin_date": "2017-09-16",
            "deadline": "2017-09-30",
            "archived": false,
            "counselor_due_date": null,
            "counselor_start_date": null,
            "attachment": "https://next-tier-test.s3.amazonaws.com/task_attachment/463891/20170927170429.png?Signature=VVJwTqE5nchXDfV80qA1TfflZU0%3D&Expires=1511838989&AWSAccessKeyId=AKIAJN7I3BGSWGOYIK4Q",
            "attachment_file_name": "dino copy.png",
            "task": 515962,
            "student": 102373,
            "institution": null,
            "verified_by": null
        },
        "note": "!"
    }
]
