import { IActScore } from '@nte/interfaces/act-score.interface';
import { ICareerClusterSurveyResult } from '@nte/interfaces/career-cluster-survey-result.interface';
import { ICareerTracker } from '@nte/interfaces/career-tracker.interface';
import { ICollegeRec } from '@nte/interfaces/college-rec.interface';
import { ICollegeTrackerItem } from '@nte/interfaces/college-tracker.interface';
import { IConnectionItem } from '@nte/interfaces/connection.interface';
import { IContactSettings } from '@nte/interfaces/contact-settings.interface';
import { ICustomScholarshipQuery } from '@nte/interfaces/custom-scholarship-query.interface';
import { IHighSchool } from '@nte/interfaces/high-school.interface';
import { IInvite } from '@nte/interfaces/invite.interface';
import { INotificationSetting } from '@nte/interfaces/notification-setting.interface';
import { IPhspSurveyResult } from '@nte/interfaces/phsp-survey-result.interface';
import { IPotentialMajor } from '@nte/interfaces/potential-major.interface';
import { ISatScore } from '@nte/interfaces/sat-score.interface';
import { IScholarshipRec } from '@nte/interfaces/scholarship-rec.interface';
import { IScholarshipTracker } from '@nte/interfaces/scholarship-tracker.interface';
import { ITagItem } from '@nte/interfaces/tag.interface';
import { StudentNote } from '@nte/models/student-note.model';

export interface IUserOverview {
  act_scores: IActScore[];
  alternate_contact_information: IContactSettings;
  career_cluster_survey_results: ICareerClusterSurveyResult;
  career_trackers: ICareerTracker[];
  class_rank_type: string;
  class_rank: number;
  class_size: number;
  connections: IConnectionItem[];
  custom_scholarship_queries: ICustomScholarshipQuery[];
  district: number;
  email: string;
  first_name: string;
  graduation_year: number;
  highschool: IHighSchool;
  id: number;
  institution_trackers: ICollegeTrackerItem[];
  invites_received: IInvite[];
  invites_sent: IInvite[];
  is_admin: boolean;
  is_phone_verified: boolean;
  last_login: string;
  last_name: string;
  meta: string;
  middle_initial: string;
  notification_settings: INotificationSetting;
  phase: string;
  phone_number: string;
  phone_type: string;
  phone_verification_code: number;
  photo_url?: string;
  phsp_survey_results: IPhspSurveyResult;
  potential_majors: IPotentialMajor[];
  profile_photo?: string;
  profile_photo_url: string;
  recommended_institutions: ICollegeRec[];
  recommended_scholarships: IScholarshipRec[];
  sat_scores: ISatScore[];
  scholarship_trackers: IScholarshipTracker[];
  stakeholder_type: string;
  student_notes: StudentNote[];
  tags: ITagItem[];
  unweighted_gpa_scale: number;
  unweighted_gpa: number;
  weighted_gpa_scale: number;
  weighted_gpa: number;
}
